// <auto-generated />
using System;
using Booking.Server.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Server.Migrations
{
    [DbContext(typeof(RoomContext))]
    [Migration("20231125185658_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Booking.Server.Entities.CustomerEntity", b =>
                {
                    b.Property<long>("IdCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCode");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Booking.Server.Entities.HotelRoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NightlyPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SleepSpotCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Booking.Server.Entities.RoomReservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HotelRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReserverIdCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HotelRoomId");

                    b.HasIndex("ReserverIdCode");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Booking.Server.Entities.RoomReservationEntity", b =>
                {
                    b.HasOne("Booking.Server.Entities.HotelRoomEntity", "HotelRoom")
                        .WithMany("Reservations")
                        .HasForeignKey("HotelRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Server.Entities.CustomerEntity", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("ReserverIdCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("HotelRoom");
                });

            modelBuilder.Entity("Booking.Server.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Booking.Server.Entities.HotelRoomEntity", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
